/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kemalOdev1App;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }


    public static int searchBoth(ArrayList<Integer> array, ArrayList<Integer> SecArray, int data){
        boolean firstFound = false;
        boolean secondFound = false;
        if(array == null && SecArray == null) 
            return -1;
        
        if(array == null && SecArray != null) 
            return -1;
        
        if(array != null && SecArray == null) 
            return -1;

        for(int i = 0;i<array.size();i++) {
            if(array.get(i) == data) {
                firstFound = true;
            }
        }

        for(int i = 0;i<SecArray.size();i++) {
            if(SecArray.get(i) == data) {
                secondFound = true;
            }
        }

        if(firstFound && secondFound) return 3;
        else if(!firstFound && secondFound) return 2;
        else if(firstFound && !secondFound) return 1;
        else return 0;

    }
}
